<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Course;

/**
 * CourseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CourseRepository extends \Doctrine\ORM\EntityRepository
{
    public function findLatest($limit = Course::NUM_ITEMS)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT c FROM AppBundle:Course c ORDER BY c.createdAt DESC'
            )
            ->setMaxResults($limit)
            ->getResult();
    }
}
